language: node_js
node_js:
 - "node"
services:
  - postgresql
before_script:
  - psql -c 'create database test_movie_api;' -U postgres
  - psql -c "create user test_user with password 'foobar';" -U postgres
  - "npm run createreviews"
  - "npm run createmovies"